import 'server-only'
import { openai }             from '@/lib/openai'
import type { StateJson }     from '@/lib/persistence/reflections'

/**
 * framework-analysis.ts — CANON-AWARE REFLECTION ANALYSIS ENGINE
 *
 * Analyzes a user's reflection submission using four canonical frameworks:
 *   1. Life Chapters (12 terrains) — where are they?
 *   2. Meaning Levels (7 levels) — why does this matter to them?
 *   3. Flow Conditions (4 conditions) — how are they moving?
 *   4. Calling Aims (4 aims) — toward what?
 *
 * Also maintains backward compatibility by outputting:
 *   - Five-dimension state assessment (intention/volition/cognition/emotion/action)
 *   - Guidance (what's happening, what's being asked, next steps, reflection prompt)
 *
 * The old Rite/Stage system is NO LONGER generated by the AI.
 * Old DB columns (rite, stage) will receive mapped values for backward compat.
 */

// ── Input ────────────────────────────────────────────────────────────────────

export type FrameworkInput = {
  dimensionScores: {
    intention: number   // aether score 0–100
    volition:  number   // fire
    cognition: number   // air
    emotion:   number   // water
    action:    number   // earth
  }

  narrative: {
    life_phase?:        string | null
    challenges?:        string | null
    direction?:         string | null
    environment?:       string | null
    recurring_pattern?: string | null
    avoidance?:         string | null
    deeper_pull?:       string | null
    energy_state?:      string | null
    energy_sources?:    string | null
  }

  newReflection:      string
  recentReflections:  string[]
  archetypeLabel?:    string | null
  growthEdge?:        string | null
  shadowTrigger?:     string | null
}

// ── Output ───────────────────────────────────────────────────────────────────

export type FrameworkOutput = {
  // Canon-aligned layers
  life_chapter: {
    name:        string
    confidence:  'low' | 'medium' | 'high'
    explanation: string
  }
  meaning_level: {
    name:        string
    confidence:  'low' | 'medium' | 'high'
    explanation: string
  }
  flow_snapshot: {
    activation:    number  // 1–10
    alignment:     number
    attunement:    number
    attentiveness: number
  }
  calling_snapshot: {
    connection:   number   // 1–10
    contribution: number
    creativity:   number
    capability:   number
  }

  // Five-dimension state assessment (retained)
  state: StateJson

  // Guidance
  guidance: {
    what_is_happening:   string
    what_is_being_asked: string
    next_steps:          string[]
    reflection_prompt:   string
  }

  reasoning_summary: string
}

// ── Helpers ──────────────────────────────────────────────────────────────────

function scoreToLevel(score: number): 'low' | 'moderate' | 'high' {
  if (score <= 40) return 'low'
  if (score <= 65) return 'moderate'
  return 'high'
}

// ── JSON Schema ──────────────────────────────────────────────────────────────

const DIM_ASSESSMENT = {
  type: 'object',
  properties: {
    level:   { type: 'string', enum: ['low', 'moderate', 'high'] },
    quality: { type: 'string', enum: ['healthy', 'compromised'] },
    note:    { type: 'string' },
  },
  required: ['level', 'quality', 'note'],
  additionalProperties: false,
} as const

const OUTPUT_SCHEMA = {
  type: 'object',
  properties: {
    life_chapter: {
      type: 'object',
      properties: {
        name:        { type: 'string', enum: ['initiation','expansion','stability','plateau','transition','disruption','contraction','reconstruction','integration','emergence','overload','renewal'] },
        confidence:  { type: 'string', enum: ['low','medium','high'] },
        explanation: { type: 'string' },
      },
      required: ['name','confidence','explanation'],
      additionalProperties: false,
    },
    meaning_level: {
      type: 'object',
      properties: {
        name:        { type: 'string', enum: ['survival','desire','belonging','achievement','awakening','integration_meaning','transcendence'] },
        confidence:  { type: 'string', enum: ['low','medium','high'] },
        explanation: { type: 'string' },
      },
      required: ['name','confidence','explanation'],
      additionalProperties: false,
    },
    flow_snapshot: {
      type: 'object',
      properties: {
        activation:    { type: 'number' },
        alignment:     { type: 'number' },
        attunement:    { type: 'number' },
        attentiveness: { type: 'number' },
      },
      required: ['activation','alignment','attunement','attentiveness'],
      additionalProperties: false,
    },
    calling_snapshot: {
      type: 'object',
      properties: {
        connection:   { type: 'number' },
        contribution: { type: 'number' },
        creativity:   { type: 'number' },
        capability:   { type: 'number' },
      },
      required: ['connection','contribution','creativity','capability'],
      additionalProperties: false,
    },
    state: {
      type: 'object',
      properties: {
        intention: DIM_ASSESSMENT,
        volition:  DIM_ASSESSMENT,
        cognition: DIM_ASSESSMENT,
        emotion:   DIM_ASSESSMENT,
        action:    DIM_ASSESSMENT,
      },
      required: ['intention','volition','cognition','emotion','action'],
      additionalProperties: false,
    },
    guidance: {
      type: 'object',
      properties: {
        what_is_happening:   { type: 'string' },
        what_is_being_asked: { type: 'string' },
        next_steps:          { type: 'array', items: { type: 'string' } },
        reflection_prompt:   { type: 'string' },
      },
      required: ['what_is_happening','what_is_being_asked','next_steps','reflection_prompt'],
      additionalProperties: false,
    },
    reasoning_summary: { type: 'string' },
  },
  required: ['life_chapter','meaning_level','flow_snapshot','calling_snapshot','state','guidance','reasoning_summary'],
  additionalProperties: false,
} as const

// ── Prompt builders ──────────────────────────────────────────────────────────

function buildSystemPrompt(): string {
  return `You are the Aetherium Reflection Engine — a canon-aware analysis system.

You analyze a user's reflection using four canonical frameworks, plus a five-dimension state assessment.

## STEP 1 — LIFE CHAPTER (where are they?)

Detect which of the 12 Life Chapters describes the user's current terrain:

Initiation — beginning something new
Expansion — momentum rising, opportunities opening
Stability — maintaining structure and rhythm
Plateau — flat progress, hidden incubation
Transition — between identities, old fading
Disruption — shock, crisis, rupture
Contraction — inward pull, grief, slowdown
Reconstruction — rebuilding after collapse
Integration — making sense of experience
Emergence — new pattern coming online
Overload — too many demands
Renewal — vitality returning

Chapters are cyclical, not linear. Base detection on situational signals in the reflection, not on scores alone.

## STEP 2 — MEANING LEVEL (why does this matter?)

Detect the dominant meaning-making lens active in this reflection:

Survival — interpreting through safety and security
Desire — interpreting through wanting, identity, pleasure
Belonging — interpreting through relationship and acceptance
Achievement — interpreting through competence and results
Awakening — interpreting through truth and awareness
Integration (meaning) — interpreting through wholeness and systems
Transcendence — interpreting through service and devotion

Use enum value "integration_meaning" for the Integration level to avoid collision with Life Chapter "integration."

## STEP 3 — FLOW CONDITIONS (how are they moving?)

Rate each condition 1–10:

Activation — energy converted into motion, willingness to begin
Alignment — values and direction congruent
Attunement — sensitive to reality, timing, self, others
Attentiveness — stable presence on what matters

## STEP 4 — CALLING AIMS (toward what?)

Rate each aim 1–10:

Connection — relationship, resonance, belonging
Contribution — service, usefulness, impact
Creativity — expression, originality
Capability — mastery, competence, discipline

## STEP 5 — FIVE-DIMENSION STATE

Assess how the person is currently showing up across five dimensions.
You are given pre-computed levels — confirm or adjust based on the reflection content.

Intention (aether) — clarity of aim, purpose
Volition (fire) — will, decisiveness, commitment
Cognition (air) — thinking, discernment
Emotion (water) — feeling, connection, regulation
Action (earth) — follow-through, embodiment

For each: level (low/moderate/high), quality (healthy/compromised), note (one sentence).

## STEP 6 — GUIDANCE

Combine all layers to generate:
- what_is_happening: one paragraph naming the situation
- what_is_being_asked: one paragraph naming what this moment requires
- next_steps: 1–3 concrete, specific actions (not themes)
- reflection_prompt: one question for the next reflection

## TONE
- Precise and grounded. No vague encouragement.
- Reference the actual content of the reflection.
- Next steps should be smallest useful actions.
- Name avoidance when present.`
}

function buildUserPrompt(input: FrameworkInput): string {
  const s = input.dimensionScores

  const narrativeBlock = Object.entries(input.narrative)
    .filter(([, v]) => v)
    .map(([k, v]) => `${k}: ${v}`)
    .join('\n')

  const priorBlock = input.recentReflections.length > 0
    ? input.recentReflections.map((r, i) => `[${i + 1}] ${r}`).join('\n')
    : '(none)'

  return `Analyze this reflection using the 6-step framework.

## NEW REFLECTION
${input.newReflection}

## PRIOR REFLECTIONS (oldest first)
${priorBlock}

## ASSESSMENT CONTEXT
${narrativeBlock || '(no narrative provided)'}

## DIMENSION SCORES (pre-computed)
Intention (aether): ${s.intention}/100 → ${scoreToLevel(s.intention)}
Volition  (fire):   ${s.volition}/100 → ${scoreToLevel(s.volition)}
Cognition (air):    ${s.cognition}/100 → ${scoreToLevel(s.cognition)}
Emotion   (water):  ${s.emotion}/100 → ${scoreToLevel(s.emotion)}
Action    (earth):  ${s.action}/100 → ${scoreToLevel(s.action)}

${input.archetypeLabel ? `Archetype: ${input.archetypeLabel}` : ''}
${input.growthEdge ? `Growth Edge: ${input.growthEdge}` : ''}
${input.shadowTrigger ? `Shadow Trigger: ${input.shadowTrigger}` : ''}

Generate the full analysis. Every output must reflect this specific person and reflection.`
}

// ── Main function ────────────────────────────────────────────────────────────

export async function runFrameworkAnalysis(
  input: FrameworkInput
): Promise<FrameworkOutput> {
  const response = await openai.chat.completions.create({
    model: 'gpt-4o',
    messages: [
      { role: 'system', content: buildSystemPrompt() },
      { role: 'user',   content: buildUserPrompt(input) },
    ],
    response_format: {
      type: 'json_schema',
      json_schema: {
        name:   'aetherium_reflection_analysis',
        strict: true,
        schema: OUTPUT_SCHEMA,
      },
    },
    temperature: 0.3,
  })

  const raw = response.choices[0]?.message?.content
  if (!raw) {
    throw new Error('runFrameworkAnalysis: no content returned')
  }

  let parsed: FrameworkOutput
  try {
    parsed = JSON.parse(raw) as FrameworkOutput
  } catch {
    throw new Error(`runFrameworkAnalysis: non-JSON response — ${raw.slice(0, 120)}`)
  }

  return parsed
}
